export const GROUPS = {
    GET: 'GET_GROUPS',
    TOGGLE: 'TOGGLE_GROUP',
    BRIGHTNESS: 'SET_GROUP_BRIGHTNESS',
    SATURATION: 'SET_GROUP_SATURATION',
    HUE: 'SET_GROUP_HUE',
}

export const LIGHTS = {
    GET: 'GET_LIGHTS',
    TOGGLE: 'TOGGLE_LIGHT',
    BRIGHTNESS: 'SET_LIGHT_BRIGHTNESS',
    SATURATION: 'SET_LIGHT_SATURATION',
    HUE: 'SET_LIGHT_HUE',
}

export default { GROUPS, LIGHTS }
